todo/urls.py
from django.urls import path


from todo.views import TaskListView, TagListView, TagUpdateView, TagDeleteView, TaskUpdateView, TaskDeleteView, \
    task_complete_view, TaskCreateView, TagCreateView

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/complite/<int:pk>", task_complete_view, name="task-complete"),
]

app_name = "todo"

todolist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, default=None, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "datetime"]

    def __str__(self):
        return f"{self.content}"

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


def task_complete_view(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/4743919.png' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row row_class">
        <div class="sidebar_ col-sm-1">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>

        <div class="content_ col-sm-11">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag' %}">Tags</a></li>
</ul>
<img src="/static/images/d39f4e7fd236bee40ba05376fda503fe.png" class="foto" alt="dasha">

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <div>
    <h1>Delete tag</h1>
    <p>Are u really want to delete a {{ tag }}?</p>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'todo:tag' %}">No, thanks</a>
    </form>
  </div>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
  <input type="submit" value="Add" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Tags</h1>
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
        Add
    </a>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.id }}</td>
        <td>{{ tag.name }}</td>
        <td>
          <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-dark">Update</a>
        </td>
        <td>
          <a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-dark">Delete</a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <div>
    <h1>Delete task?</h1>
    <p>Are u really want to delete a {{ task }}?</p>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'todo:index' %}">No, thanks</a>
    </form>
  </div>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} a task for yourself</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <input type="submit" value="Create" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% for task in task_list %}
    <p>
      <strong>
        {{ task.content }}
        {% if task.is_done %}
          <span class="text-success">Done</span>
        {% else %}
          <span class="text-danger">Not done</span>
        {% endif %}
      </strong>
    </p>
    {%  if task.is_done %}
      <a href="{% url 'todo:task-complete' pk=task.id %}" class="btn btn-dark link-to-page">Undo</a>
    {% else %}
      <a href="{% url 'todo:task-complete' pk=task.id %}" class="btn btn-success link-to-page">Compete</a>
    {% endif %}
    <p>
      Created: {{ task.datetime }}
      {% if task.deadline %}
        Deadline: {{ task.deadline }}
      {% endif %}
    </p>
    <p>
      Tags:
      {% for tag in task.tags.all %}
        {{ tag.name }}
      {% endfor %}
      <a href="{% url 'todo:task-update' pk=task.id %}" class="btn btn-link">Update</a>
      <a href="{% url 'todo:task-delete' pk=task.id %}" class="btn btn-link">Delete</a>
    </p>
    <hr>
  {% endfor %}
{% endblock %}